# Generated by Django 5.1.1 on 2024-10-18 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_api'),
    ]

    operations = [
        migrations.DeleteModel(
            name='api',
        ),
    ]
