# Generated by Django 5.1.1 on 2024-10-22 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
