# Generated by Django 5.1.1 on 2024-10-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_first_name_user_name_remove_user_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='pseudo',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='user@example.com', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='Doe', max_length=100),
        ),
    ]
